### ISSUE TITLE
RELEASE 1.1.1

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1259]
## TODO - RELEASE
- [x] Merge remaining PRs
- [x] Update demos (not necessary)
- [x] Create Python installers
- [x] Test Python installers
- [x] Create Windows installers
- [x] Test Windows installers
- [x] Create Release in GitHub
- [x] Update DOI in `README.rst` and `citing.rst`  
- [x] Test Bundle installer with admin rights
- [x] Test Bundle installer with user without admin rights
- [x] Upload docs
- [x] Upload to pypi
- [x] Update conda recipe
- [x] Upload to GH
- [x] Update website
- [x] Announce in mailing list

**Comment by francisco-dlp** [comment]
There seems to be a problem with zenodo, we have a new DOI for v1.1.1 but it seems not be be registered http://dx.doi.org/10.5281/zenodo.60766. I suspect that this is because I uploaded a v1.1.1 tag yesterday and I deleted it afterwards. I have tried adding a v1.1.1+doi and a v1.1.1-doi tag release in GH without success. Any ideas?

If nobody has a better idea, I propose to release v1.1.2 instead.

**Comment by francisco-dlp** [comment]
As we're running out of time (the release was planned for yesterday and delayed due to problems with the bundle as usual) I'll go for the v1.1.2 solution.

**Comment by francisco-dlp** [comment]
The situation stays the same after creating a v1.1.2 release. I've written to zenodo about this. I'll wait until this evening for their reply, but, if they don't reply today, I suggest to release v1.1.1 without the doi and add the doi once available.
