### ISSUE TITLE
Changes to default hyperspy preferences

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1556]
Following #1555, where old default preferences (kept in `~/.hyperspy/hyperspyrc`) broke hyperspy for me, there is a suggestion to remove some of the entries in the preferences file to prevent this from occurring again in the future. In particular, @francisco-dlp is suggesting removing the export file format entries (there are three, `default_export_format`, `export_loadings_default_file_format` and `export_factors_default_file_format`).

Would the users sorely miss the ability to set default settings for the export format? What do we think?

# TODO list

* [x] General.default_file_format
* [x]  Model.default_fitter
* [x]  Machine_learning.export factors(loadings)
* [x]  Machine_learning.multiple_files
* [x]  Machine_learning.same_window
* [x] All the EELS ones except for gos_directory
* [x] All plotting ones

**Comment by francisco-dlp** [comment]
These are the ones that, in my mind, it would be good to remove:

* [ ] General.default_file_format
* [ ]  Model.default_fitter
* [ ]  Machine_learning.export factors(loadings)
* [ ]  Machine_learning.multiple_files
* [ ]  Machine_learning.same_window
* [ ] All the EELS ones except for gos_directory
* [ ] All the EDS ones
* [ ] Plot.pylab_inline (this is no longer necessary)

Added list to header.

**Comment by francisco-dlp** [comment]
This one technically may require going to RnM. However, it is unlikely that this is going to break anybody's code as this just have to do with customising defaults. Hence, I would suggest that it goes to Rnm instead. Do others agree with targetting Rnm and removing the items above?

**Comment by francisco-dlp** [comment]
The overall aim of this proposal is to make hyperspy scripts more portable.
