### ISSUE TITLE
Splitting HyperSpy progress

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1599]
Issue to track HyperSpy splitting progress. Original discussion @  #821.

* [x] GUI toolkit register - ipywidgets [WIP in #1544] 
    * [x] GUI - ipywidgets #1544]
    * [x] GUI - traitsui #1544
* [x] Split the IO features into their own package, RosettaScIO. See for the implementation ~#2174~ #2972 and #1978 for the discussion.
* [x] Register external components, models and signals. See #2180.
* [ ] Split the electron microscopy features into their own package. ~(Waiting for #2180 to be ready.)~
* [ ] Merge as many pending PRs as possible before the split.

**Comment by francisco-dlp** [comment]
Splitting the signals into packages simply requires a mechanism to register new signals and components similar to the one in #1544 that registers UI toolkit. Once such a method is ready, we could reorganise the code of the specialise signals into separate folders in the hyperspy root folder for the 1.x series, so that releasing v2.0 would simply consist on moving those folder to their own repositories inside the hyperspy organisation umbrella.

**Comment by thomasaarholt** [comment]
Could someone propose how one would install hyperspy after it has been split? I'm wondering how user-friendly conda will be with this.

Say, if I wanted (hypothetically) the basic hyperspy module, the imaging module, the ipywidgets gui and the eels module. How would I install this?

**Comment by francisco-dlp** [comment]
Does the following look reasonable?

```bash

conda install hyperspy-core hyperspy-visualization hyperspy-gui-ipywidgets hyperspy-tem-eels

```

**Comment by thomasaarholt** [comment]
That looks good. I assume hyperspy-visualization (etc) would depend on hyperspy-core.

Are there any examples of other code that is split in this sense? There may be lessons worth learning from other libraries. I guess jupyter is a good example of this.

**Comment by thomasaarholt** [comment]
I'm also missing an idea of how the io-plugin register will be handled. Do we have a clear plan of how this should be implemented?

- A method for installing the io plugins separately
- Preferences support for turning plugins on and off (?)

I assume creating individual modules for each plugin is the way forward, although this has the potential to get pretty messy?

Is there a way of creating a "package deal" for instance for installing hyperspy-core, -visualization, -tem-eels and all the io plugins? I fear that having to type out the `conda install` for each plugin would create a tedious installation procedure and a barrier to future users.

**Comment by magnunor** [comment]
With regards to the file reading and writing (after this came up with the Merlin binary reader in https://github.com/hyperspy/hyperspy/issues/1942, https://github.com/hyperspy/hyperspy/pull/1943 and [fpd#16](https://gitlab.com/fpdpy/fpd/issues/16)), it would be nice to discuss how a separate IO library can look like.

I think file reading (and writing) is potentially useful for people outside of the HyperSpy community, so we should make it as easy as possible for the wider community to use it.

- Depend as much as possible on the "standard" scientific python libraries such as NumPy, SciPy, h5py, ...
- Have a fairly general name, maybe without a HyperSpy prefix to make it clear that the library doesn't require HyperSpy to work (`pyemfile`?)
- The file reader can return the same thing as it does now, which is a list of the datasets in a file. With the data as numpy objects, and axes/metadata info in dicts. (This means the current reader functionality can almost be copied without changing anything).
- The file writer would require a little tweaking, but the input should be the same as the file reader output.
- The repository itself can be in HyperSpy's github group

**Comment by francisco-dlp** [comment]
Good points. I think that for such a package it would make sense to change the license to e.g. BSD. I actually wonder if it wouldn't even make sense to have a separate package for each format plus a hyperspy EM formats package that depends on all of them and performs the HyperSpy integration steps i.e. metadata mapping etc.

**Comment by magnunor** [comment]
What would be the benefit of having different formats in different packages? I fear that something like that would add a lot of extra complexity, since it would mean adding 17 extra packages. That would potentially make it harder to add new formats, since it would require each new format to include its own repository, adding to pip, conda, ... I guess the repository could just be a copy of one of the others.

How is this normally done in the wider scientific python ecosystem?

**Comment by ericpre** [comment]
Having one package for all io plugins would be more simple and the required dependencies for each specific reader/writer could be made optional. I guess that it should be feasible to load each io plugin only when required. One io package will also avoid having to do two PRs to the hyperspy aware package and the non hyperspy aware package.
The current dictionary definition of the io reader in hyperspy seems to be a fairly good pattern. Someone not interested in the `axes` or `metadata` could just ignore it.

Would be worth starting to setup this package with the `.mib` format with a temporary wrapper in hyperspy for 1.4? It would be good if we could experiment it first, define a pattern and a write io plugin template. So that for 2.0, we can adapt the current io plugins consistently (main difficulties will possibly be the writers, as mentioning by @magnunor).

**Comment by magnunor** [comment]
Testing this with the `.mib` format for the 1.4 release sounds like a good idea!

@dnjohnstone, @M0hsend: what do you think? We could start with the implementation done in pyxem, and then modify it as necessary.

**Comment by M0hsend** [comment]
Sorry for the delay in getting back to you @magnunor (was on paternity leave for a while)
Any updates on this? At ePSIC we would like to have mib reader integrated into main repository of hyperspy asap to run automated processing on our data cluster.

**Comment by magnunor** [comment]
Not much. Some discussion here: https://github.com/hyperspy/hyperspy/issues/1978. The next step could be to simply copy-paste the `pyxem` implementation into a new separate IO-library (as discussed in https://github.com/hyperspy/hyperspy/issues/1978), since the `pyxem` implementation seems to be the most complete one.

But I'd like to get some feedback from @dnjohnstone and/or @pc494 before doing such a thing.

**Comment by magnunor** [comment]
I've also implemented a [very simple MIB-reader](http://pixstem.org/api.html#pixstem.io_tools.load_binary_merlin_signal) in `pixStem`, and the `fpd` library has a more fancy function for loading the MIB data now: https://gitlab.com/fpdpy/fpd/blob/master/fpd/fpd_file.py#L1832

**Comment by dnjohnstone** [comment]
Yes you're more than welcome to just take that out of pyxem - @M0hsend wrote pretty much all of that anyway! It should go in separate io_plugins really it's just in pyxem for our own convenience.

**Comment by thomasaarholt** [comment]
@kociak suggests we might take a look at Nion Swift for an approach to registering different modules within hyperspy.

**Comment by kociak** [comment]
following @thomasaarholt sticky note. NION Swift has a nice plugins feature, which could be handy to address some points related to the splitting. The plugins are just python module, with a name belonging to a chosen namespace (for example in hyperspy, could be hyperspy_plug-ins). In the ```__init__.py``` of the module you define a special singleton class which will be provided with an API object which is an interface to the core NION Swift API and an extension id. So, the plug in develloper easily access SWIFT interface and tools. And Swift can keep track of all extensions, and decide not to load a plug-in if it is not hyperspy compliant or buggy. The code is here: https://github.com/nion-software/nionswift/blob/master/nion/swift/model/PlugInManager.py
And the documentation (for plug in devellopers) is here:
https://nionswift.readthedocs.io/en/stable/python_extensions.html

**Comment by francisco-dlp** [comment]
PRs #2180 and #2174 implement the main mechanisms required to register external objects and ultimately split HyperSpy. I have updated the header accordingly.

**Comment by jlaehne** [comment]
Splitting the IO features into RosettaSciIO is now prepared (and almost ready) in PR #2972.

**Comment by jat255** [comment]
@ericpre This one can be closed too, I think.
