### ISSUE TITLE
RELEASE v1.3.1

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#1891]
Currently HyperSpy is difficult to install using python installers and anaconda due to incompatibilities with new versions of external libraries that has been released since HyperSpy's latest release almost a year ago. Also, many bugs has been fixed and the bundle, albeit working, ships with old version of the python libraries. Therefore, I think that the time is ripe for a patch release, for example late next week.

In my mind, the main issues to fix before releasing are:

* [ ] ~~Fix the context menu entries in the bundle~~ see #1897 and #1913
    * [ ] ~~https://github.com/hyperspy/hyperspy-bundle/pull/19~~
    * [ ] ~~https://github.com/hyperspy/hyperspyUI/pull/135 (if there is time, this is not necessary but if we are working on the desktop integration script, it may be both sorting out both windows and linux at the same time.)~~
* [ ] Review, finalize and merge:
    * [x] https://github.com/hyperspy/hyperspyUI/pull/150
    * [x] https://github.com/hyperspy/hyperspy-bundle/pull/22
    * [x] #1890
    * [x] #1648
    * [x] #1699
    * [x] #1830
    * [x] #1832
    * [x] #1851
    * [x] #1875
    * [x] #1879 (waiting for author)
    * [x] #1831
    * [ ] #1802 (waiting for author)
    * [x] #1700
    * [x] #1689 (waiting for author, maybe somebody should take over the branch)
    * [ ] ~~#1870  (waiting for author)~~ set to v1.4 milestone
* [x] Review and merge (if ready) all other bug fixing PRs
* [x] Release hyperspy-gui-traitsui

Does the release date and plan sound good? Am I forgetting something in the list above? (If yes, feel free to edit it as appropriate).

Of course, there is plenty of new material in Rnm, so v1.4 should follow soon after v1.3.1.

**Comment by ericpre** [comment]
I have added a few more PR to merge, it looks to me that most of them should not take very long. Others may be bonus! :smirk:

**Comment by francisco-dlp** [comment]
Thanks @ericpre. I have added a few more. I have also added some bugs to the new [v1.3.1 milestone](https://github.com/hyperspy/hyperspy/milestone/29) that I consider that are enough critical (yet easy-to-fix enough) to be ready by next week.

**Comment by thomasaarholt** [comment]
Would be good to fix #1882 as well as that will definitely pop up again.

**Comment by thomasaarholt** [comment]
I can try saving a small EELS spectra, deleting some of the tags and loading that.

**Comment by francisco-dlp** [comment]
The self-imposed release deadline is today. Although we're closed to close most of the issues and PRs in our target for this release, I don't think that we'll manage to do it today. Should we push the release to early next week?

**Comment by francisco-dlp** [comment]
Btw, I've updated the conda recipe in https://github.com/conda-forge/hyperspy-feedstock/pull/15 to build Rnp and it works fine.

**Comment by thomasaarholt** [comment]
Can we make a release of the traitsui/ipywidgets guise as well?

Yes to delaying release.

>

**Comment by francisco-dlp** [comment]
I've added hyperspy-gui-traitsui release to the TODO list. Why do we need a hyperspy-gui-ipywidgets release?

**Comment by francisco-dlp** [comment]
By the way, do you think that you'll have time to work on #1870 for this release?

**Comment by thomasaarholt** [comment]
We don't. I just remembered that there had been a couple of commits to the
traitsui one since my own PR, and incorrectly assumed that some of those
had been applied to the ipywidgets one as well.

**Comment by thomasaarholt** [comment]
Yes. My Sunday is set to work on it.

**Comment by francisco-dlp** [comment]
hyperspy-gui-traitsui released.

**Comment by francisco-dlp** [comment]
We'll release tomorrow.

**Comment by ericpre** [comment]
All done and the hyperspy-bundle has been released too:
https://github.com/hyperspy/hyperspy-bundle/releases
